require File.expand_path(File.dirname(__FILE__) + '/zomato/api.rb')
require File.expand_path(File.dirname(__FILE__) + '/zomato/city.rb')
require File.expand_path(File.dirname(__FILE__) + '/zomato/locality.rb')
require File.expand_path(File.dirname(__FILE__) + '/zomato/zone.rb')
require File.expand_path(File.dirname(__FILE__) + '/zomato/subzone.rb')
require File.expand_path(File.dirname(__FILE__) + '/zomato/restaurant.rb')
require File.expand_path(File.dirname(__FILE__) + '/zomato/cuisine.rb')
require File.expand_path(File.dirname(__FILE__) + '/zomato/base.rb')